version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb-milestone
    volumes:
      - ~/mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=milestone
      - MONGO_INITDB_ROOT_USERNAME=milestone
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - '27017:27017'